-- =====================================================
-- Seed data for development
-- =====================================================
-- NOTE: Test Manager Account creation has been moved to Admin API
-- This is INTENTIONALLY EMPTY because:
--
-- 1. Creating auth.users directly via SQL is problematic
-- 2. The Admin API is the proper way to create users
-- 3. The handle_new_user() trigger will auto-create profiles
--
-- To create the test manager, use:
--   curl -X POST "https://vzohmhsclrmhleyndtlz.supabase.co/auth/v1/admin/users" \
--     -H "apikey: SERVICE_ROLE_KEY" \
--     -d '{"email":"manager@test.com","password":"TestPass123!","email_confirm":true}'
--
-- Then the trigger will automatically create the profile.
-- =====================================================
